<?php
/********************************************************************
Product		: Payage
Date		: 24 January 2022
Copyright	: Les Arbres Design 2014-2022
Contact		: https://www.lesarbresdesign.info
Licence		: GNU General Public License
*********************************************************************/
defined('_JEXEC') or die('Restricted Access');

class PayageCountryHelper
{

function __construct()
{
    $this->createCountries();
}

//-------------------------------------------------------------------------------
// Create a table of countries by region
// Region European Union + UK is useful for analysis of historical data
//
function create_regions()
{
    $this->regions = array(
        0 => array('name' => 'Europe', 'pie_chart' => true,
            'members' => array('AX','AL','AD','AT','BA','BE','BG','HR','CH','CZ','DK','EE','FI','FO','FR','DE','GB','GG','GI','GL','GR','HU','IS','IE',
            'IM','IT','JE','LI','LV','LT','LU','MC','ME','MK','MT','NL','NO','PL','PT','RO','RS','SJ','SK','SI','SM','ES','SE','VA')),
        1 => array('name' => 'European Union + UK', 'pie_chart' => false,
            'members' => array('AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GB','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE')),
        2 => array('name' => 'European Union', 'pie_chart' => false,
            'members' => array('AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE')),
        3 => array('name' => 'North & Central America', 'pie_chart' => true,
            'members' => array('US','CA','AI','AW','BS','BB','BM','KY','CU','DM','DO','GD','GP','HT','JM','MQ','MS','PR','KN','LC','VC','TT','TC','VG','VI','PM')),
        4 => array('name' => 'South America', 'pie_chart' => true,
            'members' => array('AR','BO','BR','CL','CO','EC','FK','GF','GY','PY','PE','SR','UY','VE')),
        5 => array('name' => 'Africa', 'pie_chart' => true,
            'members' => array('DZ','EG','LY','MA','TN','EH','AO','BJ','BW','BF','BI','CM','CV','CF','TD','KM','CG','CD','CI','DJ','GQ','ER','GA','GM','GH','GN','GW',
            'KE','LS','LR','MG','MW','ML','MR','MU','YT','MZ','NA','NE','NG','RE','RW','SH','ST','SN','SC','SL','SO','ZA','SD','SZ','TZ','TG','UG','ZM','ZW')),
        6 => array('name' => 'Asia', 'pie_chart' => true,
            'members' => array('BD','BT','IO','BN','KH','IN','ID','LA','MY','MV','MM','NP','PH','SG','LK','TH','TL','VN',
            'CN','HK','JP','KP','KR','MO','MN','TW','BY','MD','RU','UA',
            'AF','AM','AZ','BH','CY','GE','IR','IQ','IL','JO','KZ','KW','KG','LB','OM','PK','PS','QA','SA','SY','TJ','TR','TM','AE','UZ','YE')),
        7 => array('name' => 'South & Southeast Asia', 'pie_chart' => false,
            'members' => array('BD','BT','IO','BN','KH','IN','ID','LA','MY','MV','MM','NP','PH','SG','LK','TH','TL','VN')),
        8 => array('name' => 'Australia', 'pie_chart' => true,
            'members' => array('AU','PG','NZ','SB','FJ','VU','AS','KI','CK','PF','GU','MH','FM','NR','NC','NU','NF','MP','PW','PN','WS','TK','TO','TV','WF')),
        9 => array('name' => 'Unknown', 'pie_chart' => true,
            'members' => array('')),
        10 => array('name' => JText::_('COM_PAYAGE_ALL_COUNTRIES'), 'pie_chart' => false,
            'members' => array())  // empty means all countries
        );
}

//-------------------------------------------------------------------------------
// Get a country name from its country code
//
function country_name($code)
{
    $upcode = strtoupper($code);
    if (isset($this->countries[$upcode]))
        return $this->countries[$upcode];
    else
        return '<span style="color:red">'.JText::_('COM_PAYAGE_UNKNOWN').'</span>';
}

//-------------------------------------------------------------------------------
// Get country details for a payment
//
function country_detail($code, $name)
{
	if (empty($code))
		return $name;				// no code so just return name, which might also be empty
	if (strlen($name) != 2)		
		return "$code ($name)";							// we have a code and a a valid name
	return $code.' ('.$this->country_name($code).')';	// we have a code but no name so get name from our table
}

//-------------------------------------------------------------------------------
// Create all the countries
//
function createCountries()
{
	$this->countries = array(
		'AF' => 'Afghanistan',
		'AX' => 'Aland Islands',
		'AL' => 'Albania',
		'DZ' => 'Algeria',
		'AS' => 'American Samoa',
		'AD' => 'Andorra',
		'AO' => 'Angola',
		'AI' => 'Anguilla',
		'AQ' => 'Antarctica',
		'AG' => 'Antigua And Barbuda',
		'AR' => 'Argentina',
		'AM' => 'Armenia',
		'AW' => 'Aruba',
		'AU' => 'Australia',
		'AT' => 'Austria',
		'AZ' => 'Azerbaijan',
		'BS' => 'Bahamas',
		'BH' => 'Bahrain',
		'BD' => 'Bangladesh',
		'BB' => 'Barbados',
		'BY' => 'Belarus',
		'BE' => 'Belgium',
		'BZ' => 'Belize',
		'BJ' => 'Benin',
		'BM' => 'Bermuda',
		'BT' => 'Bhutan',
		'BO' => 'Bolivia',
		'BA' => 'Bosnia And Herzegovina',
		'BW' => 'Botswana',
		'BV' => 'Bouvet Island',
		'BR' => 'Brazil',
		'IO' => 'British Indian Ocean Territory',
		'BN' => 'Brunei Darussalam',
		'BG' => 'Bulgaria',
		'BF' => 'Burkina Faso',
		'BI' => 'Burundi',
		'KH' => 'Cambodia',
		'CM' => 'Cameroon',
		'CA' => 'Canada',
		'CV' => 'Cape Verde',
		'KY' => 'Cayman Islands',
		'CF' => 'Central African Republic',
		'TD' => 'Chad',
		'CL' => 'Chile',
		'CN' => 'China',
		'CX' => 'Christmas Island',
		'CC' => 'Cocos (Keeling) Islands',
		'CO' => 'Colombia',
		'KM' => 'Comoros',
		'CG' => 'Congo',
		'CD' => 'Congo, The Democratic Republic Of The',
		'CK' => 'Cook Islands',
		'CR' => 'Costa Rica',
		'CI' => 'Cote D\'ivoire',
		'HR' => 'Croatia',
		'CU' => 'Cuba',
		'CY' => 'Cyprus',
		'CZ' => 'Czech Republic',
		'DK' => 'Denmark',
		'DJ' => 'Djibouti',
		'DM' => 'Dominica',
		'DO' => 'Dominican Republic',
		'EC' => 'Ecuador',
		'EG' => 'Egypt',
		'SV' => 'El Salvador',
		'GQ' => 'Equatorial Guinea',
		'ER' => 'Eritrea',
		'EE' => 'Estonia',
		'ET' => 'Ethiopia',
		'FK' => 'Falkland Islands (Malvinas)',
		'FO' => 'Faroe Islands',
		'FJ' => 'Fiji',
		'FI' => 'Finland',
		'FR' => 'France',
		'GF' => 'French Guiana',
		'PF' => 'French Polynesia',
		'TF' => 'French Southern Territories',
		'GA' => 'Gabon',
		'GM' => 'Gambia',
		'GE' => 'Georgia',
		'DE' => 'Germany',
		'GH' => 'Ghana',
		'GI' => 'Gibraltar',
		'GR' => 'Greece',
		'GL' => 'Greenland',
		'GD' => 'Grenada',
		'GP' => 'Guadeloupe',
		'GU' => 'Guam',
		'GT' => 'Guatemala',
		'GG' => 'Guernsey',
		'GN' => 'Guinea',
		'GW' => 'Guinea-Bissau',
		'GY' => 'Guyana',
		'HT' => 'Haiti',
		'HM' => 'Heard Island And Mcdonald Islands',
		'VA' => 'Holy See (Vatican City State)',
		'HN' => 'Honduras',
		'HK' => 'Hong Kong',
		'HU' => 'Hungary',
		'IS' => 'Iceland',
		'IN' => 'India',
		'ID' => 'Indonesia',
		'IR' => 'Iran, Islamic Republic Of',
		'IQ' => 'Iraq',
		'IE' => 'Ireland',
		'IM' => 'Isle Of Man',
		'IL' => 'Israel',
		'IT' => 'Italy',
		'JM' => 'Jamaica',
		'JP' => 'Japan',
		'JE' => 'Jersey',
		'JO' => 'Jordan',
		'KZ' => 'Kazakhstan',
		'KE' => 'Kenya',
		'KI' => 'Kiribati',
		'KP' => 'Korea, Democratic People\'s Republic Of',
		'KR' => 'Korea, Republic Of',
		'KW' => 'Kuwait',
		'KG' => 'Kyrgyzstan',
		'LA' => 'Lao People\'s Democratic Republic',
		'LV' => 'Latvia',
		'LB' => 'Lebanon',
		'LS' => 'Lesotho',
		'LR' => 'Liberia',
		'LY' => 'Libyan Arab Jamahiriya',
		'LI' => 'Liechtenstein',
		'LT' => 'Lithuania',
		'LU' => 'Luxembourg',
		'MO' => 'Macao',
		'MK' => 'Macedonia, The Former Yugoslav Republic Of',
		'MG' => 'Madagascar',
		'MW' => 'Malawi',
		'MY' => 'Malaysia',
		'MV' => 'Maldives',
		'ML' => 'Mali',
		'MT' => 'Malta',
		'MH' => 'Marshall Islands',
		'MQ' => 'Martinique',
		'MR' => 'Mauritania',
		'MU' => 'Mauritius',
		'YT' => 'Mayotte',
		'MX' => 'Mexico',
		'FM' => 'Micronesia, Federated States Of',
		'MD' => 'Moldova, Republic Of',
		'MC' => 'Monaco',
		'MN' => 'Mongolia',
		'MS' => 'Montserrat',
		'MA' => 'Morocco',
		'MZ' => 'Mozambique',
		'MM' => 'Myanmar',
		'NA' => 'Namibia',
		'NR' => 'Nauru',
		'NP' => 'Nepal',
		'NL' => 'Netherlands',
		'AN' => 'Netherlands Antilles',
		'NC' => 'New Caledonia',
		'NZ' => 'New Zealand',
		'NI' => 'Nicaragua',
		'NE' => 'Niger',
		'NG' => 'Nigeria',
		'NU' => 'Niue',
		'NF' => 'Norfolk Island',
		'MP' => 'Northern Mariana Islands',
		'NO' => 'Norway',
		'OM' => 'Oman',
		'PK' => 'Pakistan',
		'PW' => 'Palau',
		'PS' => 'Palestinian Territory, Occupied',
		'PA' => 'Panama',
		'PG' => 'Papua New Guinea',
		'PY' => 'Paraguay',
		'PE' => 'Peru',
		'PH' => 'Philippines',
		'PN' => 'Pitcairn',
		'PL' => 'Poland',
		'PT' => 'Portugal',
		'PR' => 'Puerto Rico',
		'QA' => 'Qatar',
		'RE' => 'Reunion',
		'RO' => 'Romania',
		'RU' => 'Russian Federation',
		'RW' => 'Rwanda',
		'SH' => 'Saint Helena',
		'KN' => 'Saint Kitts And Nevis',
		'LC' => 'Saint Lucia',
		'PM' => 'Saint Pierre And Miquelon',
		'VC' => 'Saint Vincent And The Grenadines',
		'WS' => 'Samoa',
		'SM' => 'San Marino',
		'ST' => 'Sao Tome And Principe',
		'SA' => 'Saudi Arabia',
		'SN' => 'Senegal',
        'RS' => 'Serbia',
        'ME' => 'Montenegro',
		'SC' => 'Seychelles',
		'SL' => 'Sierra Leone',
		'SG' => 'Singapore',
		'SK' => 'Slovakia',
		'SI' => 'Slovenia',
		'SB' => 'Solomon Islands',
		'SO' => 'Somalia',
		'ZA' => 'South Africa',
		'GS' => 'South Georgia And The South Sandwich Islands',
		'ES' => 'Spain',
		'LK' => 'Sri Lanka',
		'SD' => 'Sudan',
		'SR' => 'Suriname',
		'SJ' => 'Svalbard And Jan Mayen',
		'SZ' => 'Swaziland',
		'SE' => 'Sweden',
		'CH' => 'Switzerland',
		'SY' => 'Syrian Arab Republic',
		'TW' => 'Taiwan, Province Of China',
		'TJ' => 'Tajikistan',
		'TZ' => 'Tanzania, United Republic Of',
		'TH' => 'Thailand',
		'TL' => 'Timor-Leste',
		'TG' => 'Togo',
		'TK' => 'Tokelau',
		'TO' => 'Tonga',
		'TT' => 'Trinidad And Tobago',
		'TN' => 'Tunisia',
		'TR' => 'Turkey',
		'TM' => 'Turkmenistan',
		'TC' => 'Turks And Caicos Islands',
		'TV' => 'Tuvalu',
		'UG' => 'Uganda',
		'UA' => 'Ukraine',
		'AE' => 'United Arab Emirates',
		'GB' => 'United Kingdom',
		'US' => 'United States',
		'UM' => 'United States Minor Outlying Islands',
		'UY' => 'Uruguay',
		'UZ' => 'Uzbekistan',
		'VU' => 'Vanuatu',
		'VE' => 'Venezuela',
		'VN' => 'Viet Nam',
		'VG' => 'Virgin Islands, British',
		'VI' => 'Virgin Islands, U.S.',
		'WF' => 'Wallis And Futuna',
		'EH' => 'Western Sahara',
		'YE' => 'Yemen',
		'ZM' => 'Zambia',
		'ZW' => 'Zimbabwe');
}

}